### ISSUE TITLE
FAVS erode brush broken

### ISSUE THREAD

**Issue by Aerodog** [boy0001/FastAsyncWorldedit#1113]
# Bug report

**Debug paste link**:
https://hastebin.com/oqosasujay.makefile

**Description of the problem:**
https://paste.md-5.net/vemetilike.java

**How to replicate**:
"/b e (erode brush type, like melt or smooth)"

Note: shading the missing dependency doesn't fix the brush. it returns a ton of different `java.lang.ArrayIndexOutOfBoundsException` when you try to use the brush.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
#1079

**Comment by boy0001** [comment]
Fixed in https://github.com/boy0001/WorldEdit/commit/c1f9120cee1b2c7c87a9c0abaa5178feb66d212f

**Comment by Aerodog** [comment]
@boy0001 The dependency is there, but the brush is still broken. It dumps prismarine everywhere and spits a lot of errors.

https://paste.md-5.net/qujifowowa.txt
