### ISSUE TITLE
[MAJOR] Pasted chests lose contents.

### ISSUE THREAD

**Issue by mercurialmusic** [boy0001/FastAsyncWorldedit#1115]
# Bug report

**Debug paste link**: https://pastebin.com/1ASUkLFW

**Description of the problem:**

Copying/Pasting a chest with any contents results in an empty pasted chest.
Also, the debugpaste command seems to be broken? I'm using:
FastAsyncWorldEdit-bukkit-18.09.04-594d72d-2030.jar
on
CraftBukkit version git-Spigot-0ede7d0-c88ae6b (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
**How to replicate**:

Place a chest. Put items in it. Copy. Paste. Open pasted chest. Cry over no items. T_T
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Combustible** [comment]
This also happens to many different blocks with NBT data - including command blocks and signs. 

If you //set air some blocks with NBT data, //undo will not restore their data either

**Comment by mibby** [comment]
I am able to confirm this issue existing as well. I'm saving schematics and builds in a 1.12.2 environment with FAWE 1.12.2 and trying to move them into a new 1.13 server with FAWE 1.13. All NBT data seems to be stripped from items in chests pasted.

Also pasting schematics that have double chests next to each other in 1.12 crashes the server with the error ```ERROR Can't find any space for item in the inventory``` spammed thousands of times in 1.13. The chests now have to be spaced out and single.

**Comment by TheRealB** [comment]
same here

**Comment by mibby** [comment]
I wish there was any word or update on FAWE for 1.13. So many problems and chest NBT copy/pasting is super important for my environment to migrate 1.12 builds to 1.13. :(

**Comment by mercurialmusic** [comment]
This has been fixed in recent builds. Closing for now. Thanks!

**Comment by mibby** [comment]
@mercurialmusic No it has not? NBT data is still not saved properly when pasting a 1.12 chest shcematic full of items with FAWE 1.13.

**Comment by mercurialmusic** [comment]
@mibby You're getting your builds from https://ci.athion.net/job/FAWE-1.13/ ? 

It's worked for me for a while, and definitely works on the build 99, but this ticket was only about simple copying and pasting, not schematics, which I have not tested. You would probably want to open a new ticket for that if there isn't one already.

**Comment by Combustible** [comment]
Schematics seem to have additional problems on top of "normal" //copy //paste. 

//copy //paste with entities & tile entities seems to work correctly now, and has for a short while. Schematics are a different story. Seems to work acceptably well with "structure" type schematics (minecraft structure block format) but neither Sponge or Schematic (the old default, now deprecated format)  work properly with tile entities. 

Should find or open a new bug report for the schematic-related problems

**Comment by mibby** [comment]
@mercurialmusic I am, yes. I'll go ahead and create a new ticket though.
