### ISSUE TITLE
SuggestInputParseException: Unkown block when using material names in config-legacy disallowed blocks section.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#1145]
Paper dev 319 (Spigot 1.13.1)
FastAsyncWorldEdit 1.13 dev 81

```
[18:10:45] [Server thread/ERROR]: [FastAsyncWorldEdit] Failed to load config.yml
[18:10:45] [Server thread/WARN]: com.boydti.fawe.command.SuggestInputParseException: Unkown block for painting
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:1058)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.util.YAMLConfiguration.lambda$load$0(YAMLConfiguration.java:85)
[18:10:45] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[18:10:45] [Server thread/WARN]: 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
[18:10:45] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[18:10:45] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[18:10:45] [Server thread/WARN]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[18:10:45] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:10:45] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.util.YAMLConfiguration.load(YAMLConfiguration.java:85)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitConfiguration.load(BukkitConfiguration.java:42)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadConfig(WorldEditPlugin.java:261)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:162)
[18:10:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.init(WorldEditPlugin.java:135)
[18:10:45] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:119)
[18:10:45] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:10:45] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:10:45] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:10:45] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:10:45] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[18:10:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94)
[18:10:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[18:10:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[18:10:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:276)
[18:10:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:326)
[18:10:45] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:230)
[18:10:45] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[18:10:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

```
    disallowed-blocks: [OAK_SAPLING, SPRUCE_SAPLING, BIRCH_SAPLING, JUNGLE_SAPLING, ACACIA_SAPLING, DARK_OAK_SAPLING, BEDROCK, WATER, LAVA, GOLD_ORE, IRON_ORE, COAL_ORE, STICKY_PISTON, DEAD_BUSH, PISTON, PISTON_HEAD, MOVING_PISTON, DANDELION, POPPY, BROWN_MUSHROOM, RED_MUSHROOM, TNT, FIRE, CHEST, REDSTONE_WIRE, DIAMOND_ORE, WHEAT, SIGN, LADDER, WALL_SIGN, REDSTONE_ORE, CACTUS, SUGAR_CANE, NETHER_PORTAL, CAKE, REPEATER, PUMPKIN_STEM, MELON_STEM, VINE, LILY_PAD, NETHER_WART, BREWING_STAND, CAULDRON, END_PORTAL, DRAGON_EGG, TRIPWIRE_HOOK, TRIPWIRE, FLOWER_POT, CARROTS, POTATOES, SKELETON_SKULL, TRAPPED_CHEST, COMPARATOR, SUNFLOWER, ITEM_FRAME, COMMAND_BLOCK, REPEATING_COMMAND_BLOCK, CHAIN_COMMAND_BLOCK, STRUCTURE_BLOCK, WHITE_BED, ORANGE_BED, MAGENTA_BED, LIGHT_BLUE_BED, YELLOW_BED, LIME_BED, PINK_BED, GRAY_BED, LIGHT_GRAY_BED, CYAN_BED, PURPLE_BED, BLUE_BED, BROWN_BED, GREEN_BED, RED_BED, BLACK_BED]
```

If you use material names in the disallowed-blocks section in the legacy config, FAWE breaks and stops loading at start-up. It outputs ```unknown block for <name>``` for every material item. Remove one from the config, then restart the server, the next one reports as an invalid block. Even though it is a valid material name in spigot.

Setting disallowed-blocks to [], FAWE loads.

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/boy0001/WorldEdit/pull/3/commits/6a3177f4e7400a05084d569ab99584b1ec9a9384
Works for me as well what Apollo wrote above

**Comment by mibby** [comment]
It seems there was a typo made by me4502 including an extra colon. However I still get this error.

```
[01:36:59] [Server thread/INFO]: [FastAsyncWorldEdit] Using com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2 as the Bukkit adapter
[01:36:59] [Server thread/ERROR]: [FastAsyncWorldEdit] Failed to load config.yml
[01:36:59] [Server thread/WARN]: com.boydti.fawe.command.SuggestInputParseException: Does not match a valid block type: minecraft:item_frame
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.world.block.BlockTypes.parse(BlockTypes.java:1058)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.util.YAMLConfiguration.lambda$load$0(YAMLConfiguration.java:85)
[01:36:59] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[01:36:59] [Server thread/WARN]: 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
[01:36:59] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[01:36:59] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[01:36:59] [Server thread/WARN]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[01:36:59] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:36:59] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.util.YAMLConfiguration.load(YAMLConfiguration.java:85)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitConfiguration.load(BukkitConfiguration.java:42)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadConfig(WorldEditPlugin.java:261)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:162)
[01:36:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.init(WorldEditPlugin.java:135)
[01:36:59] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:119)
[01:36:59] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:36:59] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:36:59] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:36:59] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:36:59] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[01:36:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94)
[01:36:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[01:36:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[01:36:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:276)
[01:36:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:326)
[01:36:59] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:230)
[01:36:59] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[01:36:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by boy0001** [comment]
item frame isn't a block, it's an entity.
