### ISSUE TITLE
Non-thread-safe functionality - conflict with NoCheatPlus. Off primary thread call to hasByPass for FIGHT_GODMODE

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#221]
FastAsync dev 185
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

See https://github.com/NoCheatPlus/Issues/issues/166#issuecomment-215668415 for relevant info about issue. 

Stripped from stacktrace.
```
com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:293), 
com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:80), 
com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69), 
com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24), 
com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300), 
com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:45), 
com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:41), 
com.boydti.fawe.object.RunnableVal2.run(RunnableVal2.java:16),
 java.lang.Thread.run(Thread.java:745)]
```
```
[22:25:44] [Craft Scheduler Thread - 383/INFO]: WorldEdit: player (in "world"): /undo
[22:25:44] [Craft Scheduler Thread - 383/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (id=-1254409192).
[22:25:44] [Craft Scheduler Thread - 383/ERROR]: [NoCheatPlus] [java.lang.Thread.getStackTrace(Thread.java:1556), fr.neatmonster.nocheatplus.utilities.CheckUtils.improperAPIAccess(CheckUtils.java:209), fr.neatmonster.nocheatplus.utilities.CheckUtils.hasBypass(CheckUtils.java:193), fr.neatmonster.nocheatplus.checks.Check.isEnabled(Check.java:221), fr.neatmonster.nocheatplus.checks.fight.FightListener.onEntityDamage(FightListener.java:498), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source), org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62), org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:867), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792), net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515), net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:191), net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321), net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768), net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156), net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257), net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139), net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:293), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:80), com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69), com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24), com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:45), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:41), com.boydti.fawe.object.RunnableVal2.run(RunnableVal2.java:16), java.lang.Thread.run(Thread.java:745)]
[22:25:44] [Craft Scheduler Thread - 383/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-1254409192).
[22:26:09] [Craft Scheduler Thread - 384/INFO]: WorldEdit: player (in "world"): sphere lava 10
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (id=1235842121).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] [java.lang.Thread.getStackTrace(Thread.java:1556), fr.neatmonster.nocheatplus.utilities.CheckUtils.improperAPIAccess(CheckUtils.java:209), fr.neatmonster.nocheatplus.utilities.CheckUtils.hasBypass(CheckUtils.java:193), fr.neatmonster.nocheatplus.checks.Check.isEnabled(Check.java:221), fr.neatmonster.nocheatplus.checks.fight.FightListener.onEntityDamage(FightListener.java:498), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source), org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62), org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:487), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:867), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792), net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515), net.minecraft.server.v1_10_R1.Entity.burnFromLava(Entity.java:447), net.minecraft.server.v1_10_R1.Entity.U(Entity.java:400), net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:185), net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321), net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768), net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156), net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257), net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139), net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:293), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:80), com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69), com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24), com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:45), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:41), com.boydti.fawe.object.RunnableVal2.run(RunnableVal2.java:16), java.lang.Thread.run(Thread.java:745)]
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (id=1621438094).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] [java.lang.Thread.getStackTrace(Thread.java:1556), fr.neatmonster.nocheatplus.utilities.CheckUtils.improperAPIAccess(CheckUtils.java:209), fr.neatmonster.nocheatplus.utilities.CheckUtils.hasBypass(CheckUtils.java:193), fr.neatmonster.nocheatplus.checks.Check.isEnabled(Check.java:221), fr.neatmonster.nocheatplus.checks.fight.FightListener.onEntityDamage(FightListener.java:498), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source), org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62), org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:867), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792), net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515), net.minecraft.server.v1_10_R1.Entity.burn(Entity.java:952), net.minecraft.server.v1_10_R1.Entity.move(Entity.java:816), net.minecraft.server.v1_10_R1.EntityLiving.g(EntityLiving.java:1711), net.minecraft.server.v1_10_R1.EntityHuman.g(EntityHuman.java:1463), net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:2005), net.minecraft.server.v1_10_R1.EntityHuman.n(EntityHuman.java:359), net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1840), net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156), net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257), net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139), net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:293), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:80), com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69), com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24), com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:45), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:41), com.boydti.fawe.object.RunnableVal2.run(RunnableVal2.java:16), java.lang.Thread.run(Thread.java:745)]
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (id=-688260918).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] [java.lang.Thread.getStackTrace(Thread.java:1556), fr.neatmonster.nocheatplus.utilities.CheckUtils.improperAPIAccess(CheckUtils.java:209), fr.neatmonster.nocheatplus.utilities.CheckUtils.hasBypass(CheckUtils.java:193), fr.neatmonster.nocheatplus.checks.Check.isEnabled(Check.java:221), fr.neatmonster.nocheatplus.checks.fight.FightListener.onEntityDamage(FightListener.java:498), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source), org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62), org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:867), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792), net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515), net.minecraft.server.v1_10_R1.Entity.U(Entity.java:392), net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:185), net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321), net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768), net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156), net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257), net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139), net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:293), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:80), com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69), com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24), com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:45), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:41), com.boydti.fawe.object.RunnableVal2.run(RunnableVal2.java:16), java.lang.Thread.run(Thread.java:745)]
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:11] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:30] [Craft Scheduler Thread - 384/INFO]: WorldEdit: player (in "world"): mask grass
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:26:37] [Craft Scheduler Thread - 384/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1621438094).
[22:29:45] [Craft Scheduler Thread - 387/INFO]: WorldEdit: player (in "world"): /drain 20 - Position: (29118.0, 62.0, 15377.0)
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (id=387097441).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] [java.lang.Thread.getStackTrace(Thread.java:1556), fr.neatmonster.nocheatplus.utilities.CheckUtils.improperAPIAccess(CheckUtils.java:209), fr.neatmonster.nocheatplus.utilities.CheckUtils.hasBypass(CheckUtils.java:193), fr.neatmonster.nocheatplus.checks.Check.isEnabled(Check.java:221), fr.neatmonster.nocheatplus.checks.fight.FightListener.onEntityDamage(FightListener.java:498), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source), org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62), org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558), org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:867), net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850), net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792), net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515), net.minecraft.server.v1_10_R1.Entity.burn(Entity.java:952), net.minecraft.server.v1_10_R1.Entity.move(Entity.java:816), net.minecraft.server.v1_10_R1.EntityLiving.g(EntityLiving.java:1606), net.minecraft.server.v1_10_R1.EntityHuman.g(EntityHuman.java:1469), net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:2005), net.minecraft.server.v1_10_R1.EntityHuman.n(EntityHuman.java:359), net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1840), net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:156), net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:257), net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139), net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:293), com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.refreshChunk(BukkitQueue_1_10.java:80), com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69), com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24), com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:45), com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:41), com.boydti.fawe.object.RunnableVal2.run(RunnableVal2.java:16), java.lang.Thread.run(Thread.java:745)]
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=387097441).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=1235842121).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=387097441).
[22:29:45] [Craft Scheduler Thread - 387/ERROR]: [NoCheatPlus] Off primary thread call to hasByPass for FIGHT_GODMODE (see earlier log with id=-688260918).
```

**Comment by boy0001** [comment]
The issue you linked contains a stracktrace that isn't from a current version of FAWE, so I'm ignoring that. The other issue has been fixed,

**Comment by mibby** [comment]
Sorry. To clarify; I linked the other stacktrace as a reference to the off-primary thread access safety explanation in case you forgot about it. 

In any case, thanks for the fix. I'll keep the problems and bugs coming your way.
