### ISSUE TITLE
NBT data does not save when copying from clipboard and pastes things invisible.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#557]
WorldEdit dev 3684
FAWE dev 705 - (FastAsyncWorldEdit-bukkit-17.05.29-a607d85-699-13.0.8.jar) http://ci.athion.net/job/FastAsyncWorldEdit/705/
Paper dev 1104 (Spigot 1.11.2)

@boy0001 Pretty serious FAWE issue that has been happening for months apparently according to some worldedit users of mine.

NBT data does not seem to be saving when you save an item to the clipboard and paste it elsewhere. Signs do not preserve text data, chests do not preserve chest content, etc. As well as any items that would have NBT data, they are pasted invisible

Signs - pastes invisible and without text.
https://gyazo.com/1455613f05bd33c2ea9dde2599da42cd

Chests - pastes invisible (not able to reshow or open) and without contents https://gyazo.com/d3ef59fb0eaa22c06900f0728c2c155a

**Comment by haelexuis** [comment]
Hi, I have same problem, with shulker boxes https://github.com/boy0001/FastAsyncWorldedit/issues/556, what is weird btw: bukkit block.getState() on location is instance of ShulkerBox, but block.getType() is BlockAir, so I must (in my plugin) copy schematic, search ShulkerBoxes, remove  them and via Bukkit sync thread place them where they have to be.

**Comment by Pangamma** [comment]
Wow, these bugs and issues are pretty frightening.... The last thing I need is more world corruption.

**Comment by Gabik21MC** [comment]
Same here on my own fork of paperspigot 1.7

**Comment by PhanaticD** [comment]
having same issue, this was done with //move : https://gyazo.com/f55a1318c65b66576053667d379928e8

**Comment by mibby** [comment]
Possibly the improved ChunkListener is what breaks things?https://github.com/boy0001/FastAsyncWorldedit/commit/b9c056c879d8b9277801d10d30f6a57209c9d6a2

**Comment by mibby** [comment]
@boy0001 Did some more testing. Broken in dev 701 http://ci.athion.net/job/FastAsyncWorldEdit/701/, works in dev 694 http://ci.athion.net/job/FastAsyncWorldEdit/694/. Can't test any builds in-between since jenkins failed to compile, so definitely one of the commits in-between is causing the breakage. My guess is something in the 'various minor' of dev 699.

Whatever is causing the breakage is possibly also related to it breaking Dynmap and McMMO chunk listeners? https://github.com/boy0001/FastAsyncWorldedit/issues/555#issuecomment-305041443
https://github.com/boy0001/FastAsyncWorldedit/commit/31d43b27d88542b4c830910dbf38a33538633785
https://github.com/boy0001/FastAsyncWorldedit/commit/f89e95de111da61e0728acf103312f116cc5e573
https://github.com/boy0001/FastAsyncWorldedit/commit/efda408b762a42bb8ffde594b7dc09e71a335ef7
https://github.com/boy0001/FastAsyncWorldedit/commit/ef6ad05c2ecc3cefbce698f9eb548a9d6d8c5eef

**Comment by Miclebrick** [comment]
This is a very big problem for me as well!

**Comment by boy0001** [comment]
Should be fixed

**Comment by Jwguy0** [comment]
Just came across this today. Definitely still an issue in 2018, at least back in the May 2018 build, 18.03.10

**Comment by Miclebrick** [comment]
open a new issue it might not be the same exact one
